source = "/media/eric/NIKON"        # Camera / memory card (mount point)
ssd    = "/mnt/ssd/CameraBackup"    # Local SSD destination
nas    = "/mnt/nas/CameraBackup"    # NAS mounted via SMB/NFS (or WireGuard VPN)

file_extensions = [
  ".MOV",
  ".NEF",
  ".JPG",
  ".MP4",
]

video_extensions = [
  ".MOV",
  ".MP4",
]
